/** 
 * Puts the content of the field_info JVMS structure generated by this FieldWriter into the given ByteVector.
 * @param output where the field_info structure must be put.
 */
void putFieldInfo(final ByteVector output){
  boolean useSyntheticAttribute=symbolTable.getMajorVersion() < Opcodes.V1_5;
  int mask=useSyntheticAttribute ? Opcodes.ACC_SYNTHETIC : 0;
  output.putShort(accessFlags & ~mask).putShort(nameIndex).putShort(descriptorIndex);
  int attributesCount=0;
  if (constantValueIndex != 0) {
    ++attributesCount;
  }
  if ((accessFlags & Opcodes.ACC_SYNTHETIC) != 0 && useSyntheticAttribute) {
    ++attributesCount;
  }
  if (signatureIndex != 0) {
    ++attributesCount;
  }
  if ((accessFlags & Opcodes.ACC_DEPRECATED) != 0) {
    ++attributesCount;
  }
  if (lastRuntimeVisibleAnnotation != null) {
    ++attributesCount;
  }
  if (lastRuntimeInvisibleAnnotation != null) {
    ++attributesCount;
  }
  if (lastRuntimeVisibleTypeAnnotation != null) {
    ++attributesCount;
  }
  if (lastRuntimeInvisibleTypeAnnotation != null) {
    ++attributesCount;
  }
  if (firstAttribute != null) {
    attributesCount+=firstAttribute.getAttributeCount();
  }
  output.putShort(attributesCount);
  if (constantValueIndex != 0) {
    output.putShort(symbolTable.addConstantUtf8(Constants.CONSTANT_VALUE)).putInt(2).putShort(constantValueIndex);
  }
  Attribute.putAttributes(symbolTable,accessFlags,signatureIndex,output);
  AnnotationWriter.putAnnotations(symbolTable,lastRuntimeVisibleAnnotation,lastRuntimeInvisibleAnnotation,lastRuntimeVisibleTypeAnnotation,lastRuntimeInvisibleTypeAnnotation,output);
  if (firstAttribute != null) {
    firstAttribute.putAttributes(symbolTable,output);
  }
}
