protected Drawable squareDrawableWithBorder(CloseableStaticBitmap closeableStaticBitmap,BorderOptions borderOptions){
  return roundedCornerDrawableWithBorder(closeableStaticBitmap,borderOptions,null);
}
