@Setup public void prepare() throws UnsupportedEncodingException {
  to_be_encoded="Jodd is set of Java microframeworks, tools and utilities, under 1.7 MB. We believe in common sense to make things simple, but not simpler. Get things done! Make your ideas! Kickstart your startup! And enjoy the coding.".getBytes("ISO-8859-1");
  to_be_decoded="JJXWIZBANFZSA43FOQQG6ZRAJJQXMYJANVUWG4TPMZZGC3LFO5XXE23TFQQHI33PNRZSAYLOMQQHK5DJNRUXI2LFOMWCA5LOMRSXEIBRFY3SATKCFYQFOZJAMJSWY2LFOZSSA2LOEBRW63LNN5XCA43FNZZWKIDUN4QG2YLLMUQHI2DJNZTXGIDTNFWXA3DFFQQGE5LUEBXG65BAONUW24DMMVZC4ICHMV2CA5DINFXGO4ZAMRXW4ZJBEBGWC23FEB4W65LSEBUWIZLBOMQSAS3JMNVXG5DBOJ2CA6LPOVZCA43UMFZHI5LQEEQEC3TEEBSW42TPPEQHI2DFEBRW6ZDJNZTS4";
}
