/** 
 * Sets up the default key bindings.
 */
public void addDefaultKeyBindings(){
  addKeyBinding("BACK_SPACE",BACKSPACE);
  addKeyBinding("C+BACK_SPACE",BACKSPACE_WORD);
  addKeyBinding("DELETE",DELETE);
  addKeyBinding("C+DELETE",DELETE_WORD);
  addKeyBinding("ENTER",INSERT_BREAK);
  addKeyBinding("TAB",INSERT_TAB);
  addKeyBinding("INSERT",OVERWRITE);
  addKeyBinding("HOME",HOME);
  addKeyBinding("END",END);
  addKeyBinding("S+HOME",SELECT_HOME);
  addKeyBinding("S+END",SELECT_END);
  addKeyBinding("C+HOME",DOCUMENT_HOME);
  addKeyBinding("C+END",DOCUMENT_END);
  addKeyBinding("CS+HOME",SELECT_DOC_HOME);
  addKeyBinding("CS+END",SELECT_DOC_END);
  addKeyBinding("PAGE_UP",PREV_PAGE);
  addKeyBinding("PAGE_DOWN",NEXT_PAGE);
  addKeyBinding("S+PAGE_UP",SELECT_PREV_PAGE);
  addKeyBinding("S+PAGE_DOWN",SELECT_NEXT_PAGE);
  addKeyBinding("LEFT",PREV_CHAR);
  addKeyBinding("S+LEFT",SELECT_PREV_CHAR);
  addKeyBinding("C+LEFT",PREV_WORD);
  addKeyBinding("CS+LEFT",SELECT_PREV_WORD);
  addKeyBinding("RIGHT",NEXT_CHAR);
  addKeyBinding("S+RIGHT",SELECT_NEXT_CHAR);
  addKeyBinding("C+RIGHT",NEXT_WORD);
  addKeyBinding("CS+RIGHT",SELECT_NEXT_WORD);
  addKeyBinding("UP",PREV_LINE);
  addKeyBinding("S+UP",SELECT_PREV_LINE);
  addKeyBinding("DOWN",NEXT_LINE);
  addKeyBinding("S+DOWN",SELECT_NEXT_LINE);
  addKeyBinding("C+ENTER",REPEAT);
}
