@Autowired public void setAuthorizationSettingTypeSuppliers(List<AuthorizationSettingTypeSupplier> authorizationSettingTypeSuppliers){
  this.authorizationSettingTypeSuppliers=authorizationSettingTypeSuppliers;
}
