static void fillMap(){
  setSuffix("","content/unknown");
  setSuffix(".uu","application/octet-stream");
  setSuffix(".exe","application/octet-stream");
  setSuffix(".ps","application/postscript");
  setSuffix(".zip","application/zip");
  setSuffix(".sh","application/x-shar");
  setSuffix(".tar","application/x-tar");
  setSuffix(".snd","audio/basic");
  setSuffix(".au","audio/basic");
  setSuffix(".wav","audio/x-wav");
  setSuffix(".gif","image/gif");
  setSuffix(".jpg","image/jpeg");
  setSuffix(".jpeg","image/jpeg");
  setSuffix(".htm","text/html");
  setSuffix(".html","text/html");
  setSuffix(".css","text/css");
  setSuffix(".java","text/javascript");
  setSuffix(".txt","text/plain");
  setSuffix(".java","text/plain");
  setSuffix(".c","text/plain");
  setSuffix(".cc","text/plain");
  setSuffix(".c++","text/plain");
  setSuffix(".h","text/plain");
  setSuffix(".pl","text/plain");
}
