public PartialDiskCacheProducer newPartialDiskCacheProducer(Producer<EncodedImage> inputProducer){
  return new PartialDiskCacheProducer(mDefaultBufferedDiskCache,mCacheKeyFactory,mPooledByteBufferFactory,mByteArrayPool,inputProducer);
}
