public ExecutionResult setExecutionException(Exception executionException){
  return new ExecutionResult(eventCounts,startTimestamp,executionLatency,userThreadLatency,failedExecutionException,executionException,executionOccurred,isExecutedInThread,collapserKey);
}
