protected DashManifest buildMediaPresentationDescription(long availabilityStartTime,long durationMs,long minBufferTimeMs,boolean dynamic,long minUpdateTimeMs,long timeShiftBufferDepthMs,long suggestedPresentationDelayMs,long publishTimeMs,ProgramInformation programInformation,UtcTimingElement utcTiming,Uri location,List<Period> periods){
  return new DashManifest(availabilityStartTime,durationMs,minBufferTimeMs,dynamic,minUpdateTimeMs,timeShiftBufferDepthMs,suggestedPresentationDelayMs,publishTimeMs,programInformation,utcTiming,location,periods);
}
