public void viewPortChangedFromScrolling(int firstVisibleIndex,int lastVisibleIndex,int firstFullyVisibleIndex,int lastFullyVisibleIndex){
  viewPortChanged(firstVisibleIndex,lastVisibleIndex,firstFullyVisibleIndex,lastFullyVisibleIndex,ViewportInfo.State.SCROLLING);
}
