public void print(OutputStream os) throws IOException {
  out(os,"<Shape ID='" + id + "' Type='Shape' LineStyle='3' FillStyle='3' TextStyle='3'>");
  out(os,"<XForm>");
  out(os,"<PinX>" + (x + width / 2) + "</PinX>");
  out(os,"<PinY>" + (y + height / 2) + "</PinY>");
  out(os,"<Width>" + width + "</Width>");
  out(os,"<Height>" + height + "</Height>");
  out(os,"<Angle>0</Angle>");
  out(os,"<FlipX>0</FlipX>");
  out(os,"<FlipY>0</FlipY>");
  out(os,"<ResizeMode>0</ResizeMode>");
  out(os,"</XForm>");
  out(os,"<Geom IX='0'>");
  out(os,"<NoFill>0</NoFill>");
  out(os,"<NoLine>0</NoLine>");
  out(os,"<NoShow>0</NoShow>");
  out(os,"<NoSnap>0</NoSnap>");
  out(os,"<MoveTo IX='1'>");
  out(os,"<X F='Width*0'>0</X>");
  out(os,"<Y F='Height*0'>0</Y>");
  out(os,"</MoveTo>");
  out(os,"<LineTo IX='2'>");
  out(os,"<X F='Width*1'>" + width + "</X>");
  out(os,"<Y F='Height*0'>0</Y>");
  out(os,"</LineTo>");
  out(os,"<LineTo IX='3'>");
  out(os,"<X F='Width*1'>" + width + "</X>");
  out(os,"<Y F='Height*1'>" + height + "</Y>");
  out(os,"</LineTo>");
  out(os,"<LineTo IX='4'>");
  out(os,"<X F='Width*0'>0</X>");
  out(os,"<Y F='Height*1'>" + height + "</Y>");
  out(os,"</LineTo>");
  out(os,"<LineTo IX='5'>");
  out(os,"<X F='Geometry1.X1'>0</X>");
  out(os,"<Y F='Geometry1.Y1'>0</Y>");
  out(os,"</LineTo>");
  out(os,"</Geom>");
  out(os,"</Shape>");
}
