public static void createChatResources(Context context,boolean fontsOnly){
synchronized (sync) {
    if (chat_msgTextPaint == null) {
      chat_msgTextPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
      chat_msgGameTextPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
      chat_msgTextPaintOneEmoji=new TextPaint(Paint.ANTI_ALIAS_FLAG);
      chat_msgTextPaintTwoEmoji=new TextPaint(Paint.ANTI_ALIAS_FLAG);
      chat_msgTextPaintThreeEmoji=new TextPaint(Paint.ANTI_ALIAS_FLAG);
      chat_msgBotButtonPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
      chat_msgBotButtonPaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    }
  }
  if (!fontsOnly && chat_msgInDrawable == null) {
    chat_infoPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_docNamePaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_docNamePaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    chat_docBackPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    chat_deleteProgressPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    chat_botProgressPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    chat_botProgressPaint.setStrokeCap(Paint.Cap.ROUND);
    chat_botProgressPaint.setStyle(Paint.Style.STROKE);
    chat_locationTitlePaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_locationTitlePaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    chat_locationAddressPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_urlPaint=new Paint();
    chat_textSearchSelectionPaint=new Paint();
    chat_radialProgressPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    chat_radialProgressPaint.setStrokeCap(Paint.Cap.ROUND);
    chat_radialProgressPaint.setStyle(Paint.Style.STROKE);
    chat_radialProgressPaint.setColor(0x9fffffff);
    chat_radialProgress2Paint=new Paint(Paint.ANTI_ALIAS_FLAG);
    chat_radialProgress2Paint.setStrokeCap(Paint.Cap.ROUND);
    chat_radialProgress2Paint.setStyle(Paint.Style.STROKE);
    chat_audioTimePaint=new TextPaint(TextPaint.ANTI_ALIAS_FLAG);
    chat_livePaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_livePaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    chat_audioTitlePaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_audioTitlePaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    chat_audioPerformerPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_botButtonPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_botButtonPaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    chat_contactNamePaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_contactNamePaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    chat_contactPhonePaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_durationPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_gamePaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_gamePaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    chat_shipmentPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_timePaint=new TextPaint(TextPaint.ANTI_ALIAS_FLAG);
    chat_adminPaint=new TextPaint(TextPaint.ANTI_ALIAS_FLAG);
    chat_namePaint=new TextPaint(TextPaint.ANTI_ALIAS_FLAG);
    chat_namePaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    chat_forwardNamePaint=new TextPaint(TextPaint.ANTI_ALIAS_FLAG);
    chat_replyNamePaint=new TextPaint(TextPaint.ANTI_ALIAS_FLAG);
    chat_replyNamePaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    chat_replyTextPaint=new TextPaint(TextPaint.ANTI_ALIAS_FLAG);
    chat_instantViewPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_instantViewPaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    chat_instantViewRectPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    chat_instantViewRectPaint.setStyle(Paint.Style.STROKE);
    chat_replyLinePaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    chat_msgErrorPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    chat_statusPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    chat_statusRecordPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    chat_statusRecordPaint.setStyle(Paint.Style.STROKE);
    chat_statusRecordPaint.setStrokeCap(Paint.Cap.ROUND);
    chat_actionTextPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_actionTextPaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    chat_actionBackgroundPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    chat_timeBackgroundPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
    chat_contextResult_titleTextPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_contextResult_titleTextPaint.setTypeface(AndroidUtilities.getTypeface("fonts/rmedium.ttf"));
    chat_contextResult_descriptionTextPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
    chat_composeBackgroundPaint=new Paint();
    Resources resources=context.getResources();
    chat_msgInDrawable=resources.getDrawable(R.drawable.msg_in).mutate();
    chat_msgInSelectedDrawable=resources.getDrawable(R.drawable.msg_in).mutate();
    chat_msgNoSoundDrawable=resources.getDrawable(R.drawable.video_muted);
    chat_msgOutDrawable=resources.getDrawable(R.drawable.msg_out).mutate();
    chat_msgOutSelectedDrawable=resources.getDrawable(R.drawable.msg_out).mutate();
    chat_msgInMediaDrawable=resources.getDrawable(R.drawable.msg_photo).mutate();
    chat_msgInMediaSelectedDrawable=resources.getDrawable(R.drawable.msg_photo).mutate();
    chat_msgOutMediaDrawable=resources.getDrawable(R.drawable.msg_photo).mutate();
    chat_msgOutMediaSelectedDrawable=resources.getDrawable(R.drawable.msg_photo).mutate();
    chat_msgOutCheckDrawable=resources.getDrawable(R.drawable.msg_check).mutate();
    chat_msgOutCheckSelectedDrawable=resources.getDrawable(R.drawable.msg_check).mutate();
    chat_msgMediaCheckDrawable=resources.getDrawable(R.drawable.msg_check).mutate();
    chat_msgStickerCheckDrawable=resources.getDrawable(R.drawable.msg_check).mutate();
    chat_msgOutHalfCheckDrawable=resources.getDrawable(R.drawable.msg_halfcheck).mutate();
    chat_msgOutHalfCheckSelectedDrawable=resources.getDrawable(R.drawable.msg_halfcheck).mutate();
    chat_msgMediaHalfCheckDrawable=resources.getDrawable(R.drawable.msg_halfcheck).mutate();
    chat_msgStickerHalfCheckDrawable=resources.getDrawable(R.drawable.msg_halfcheck).mutate();
    chat_msgOutClockDrawable=resources.getDrawable(R.drawable.msg_clock).mutate();
    chat_msgOutSelectedClockDrawable=resources.getDrawable(R.drawable.msg_clock).mutate();
    chat_msgInClockDrawable=resources.getDrawable(R.drawable.msg_clock).mutate();
    chat_msgInSelectedClockDrawable=resources.getDrawable(R.drawable.msg_clock).mutate();
    chat_msgMediaClockDrawable=resources.getDrawable(R.drawable.msg_clock).mutate();
    chat_msgStickerClockDrawable=resources.getDrawable(R.drawable.msg_clock).mutate();
    chat_msgInViewsDrawable=resources.getDrawable(R.drawable.msg_views).mutate();
    chat_msgInViewsSelectedDrawable=resources.getDrawable(R.drawable.msg_views).mutate();
    chat_msgOutViewsDrawable=resources.getDrawable(R.drawable.msg_views).mutate();
    chat_msgOutViewsSelectedDrawable=resources.getDrawable(R.drawable.msg_views).mutate();
    chat_msgMediaViewsDrawable=resources.getDrawable(R.drawable.msg_views).mutate();
    chat_msgStickerViewsDrawable=resources.getDrawable(R.drawable.msg_views).mutate();
    chat_msgInMenuDrawable=resources.getDrawable(R.drawable.msg_actions).mutate();
    chat_msgInMenuSelectedDrawable=resources.getDrawable(R.drawable.msg_actions).mutate();
    chat_msgOutMenuDrawable=resources.getDrawable(R.drawable.msg_actions).mutate();
    chat_msgOutMenuSelectedDrawable=resources.getDrawable(R.drawable.msg_actions).mutate();
    chat_msgMediaMenuDrawable=resources.getDrawable(R.drawable.video_actions);
    chat_msgInInstantDrawable=resources.getDrawable(R.drawable.msg_instant).mutate();
    chat_msgOutInstantDrawable=resources.getDrawable(R.drawable.msg_instant).mutate();
    chat_msgErrorDrawable=resources.getDrawable(R.drawable.msg_warning);
    chat_muteIconDrawable=resources.getDrawable(R.drawable.list_mute).mutate();
    chat_lockIconDrawable=resources.getDrawable(R.drawable.ic_lock_header);
    chat_msgBroadcastDrawable=resources.getDrawable(R.drawable.broadcast3).mutate();
    chat_msgBroadcastMediaDrawable=resources.getDrawable(R.drawable.broadcast3).mutate();
    chat_msgInCallDrawable=resources.getDrawable(R.drawable.ic_call).mutate();
    chat_msgInCallSelectedDrawable=resources.getDrawable(R.drawable.ic_call).mutate();
    chat_msgOutCallDrawable=resources.getDrawable(R.drawable.ic_call).mutate();
    chat_msgOutCallSelectedDrawable=resources.getDrawable(R.drawable.ic_call).mutate();
    chat_msgCallUpGreenDrawable=resources.getDrawable(R.drawable.ic_call_made_green_18dp).mutate();
    chat_msgCallDownRedDrawable=resources.getDrawable(R.drawable.ic_call_received_green_18dp).mutate();
    chat_msgCallDownGreenDrawable=resources.getDrawable(R.drawable.ic_call_received_green_18dp).mutate();
    calllog_msgCallUpRedDrawable=resources.getDrawable(R.drawable.ic_call_made_green_18dp).mutate();
    calllog_msgCallUpGreenDrawable=resources.getDrawable(R.drawable.ic_call_made_green_18dp).mutate();
    calllog_msgCallDownRedDrawable=resources.getDrawable(R.drawable.ic_call_received_green_18dp).mutate();
    calllog_msgCallDownGreenDrawable=resources.getDrawable(R.drawable.ic_call_received_green_18dp).mutate();
    chat_msgAvatarLiveLocationDrawable=resources.getDrawable(R.drawable.livepin).mutate();
    chat_inlineResultFile=resources.getDrawable(R.drawable.bot_file);
    chat_inlineResultAudio=resources.getDrawable(R.drawable.bot_music);
    chat_inlineResultLocation=resources.getDrawable(R.drawable.bot_location);
    chat_redLocationIcon=resources.getDrawable(R.drawable.map_pin).mutate();
    chat_msgInShadowDrawable=resources.getDrawable(R.drawable.msg_in_shadow);
    chat_msgOutShadowDrawable=resources.getDrawable(R.drawable.msg_out_shadow);
    chat_msgInMediaShadowDrawable=resources.getDrawable(R.drawable.msg_photo_shadow);
    chat_msgOutMediaShadowDrawable=resources.getDrawable(R.drawable.msg_photo_shadow);
    chat_botLinkDrawalbe=resources.getDrawable(R.drawable.bot_link);
    chat_botInlineDrawable=resources.getDrawable(R.drawable.bot_lines);
    chat_systemDrawable=resources.getDrawable(R.drawable.system);
    chat_contextResult_shadowUnderSwitchDrawable=resources.getDrawable(R.drawable.header_shadow).mutate();
    chat_attachButtonDrawables[0]=new AttachCameraDrawable();
    chat_attachButtonDrawables[1]=createCircleDrawableWithIcon(AndroidUtilities.dp(54),R.drawable.attach_gallery);
    chat_attachButtonDrawables[2]=createCircleDrawableWithIcon(AndroidUtilities.dp(54),R.drawable.attach_video);
    chat_attachButtonDrawables[3]=createCircleDrawableWithIcon(AndroidUtilities.dp(54),R.drawable.attach_audio);
    chat_attachButtonDrawables[4]=createCircleDrawableWithIcon(AndroidUtilities.dp(54),R.drawable.attach_file);
    chat_attachButtonDrawables[5]=createCircleDrawableWithIcon(AndroidUtilities.dp(54),R.drawable.attach_contact);
    chat_attachButtonDrawables[6]=createCircleDrawableWithIcon(AndroidUtilities.dp(54),R.drawable.attach_location);
    chat_attachButtonDrawables[7]=createCircleDrawableWithIcon(AndroidUtilities.dp(54),R.drawable.attach_close);
    chat_attachButtonDrawables[8]=createCircleDrawableWithIcon(AndroidUtilities.dp(54),R.drawable.attach_send);
    chat_attachButtonDrawables[9]=createCircleDrawableWithIcon(AndroidUtilities.dp(54),R.drawable.attach_polls);
    chat_cornerOuter[0]=resources.getDrawable(R.drawable.corner_out_tl);
    chat_cornerOuter[1]=resources.getDrawable(R.drawable.corner_out_tr);
    chat_cornerOuter[2]=resources.getDrawable(R.drawable.corner_out_br);
    chat_cornerOuter[3]=resources.getDrawable(R.drawable.corner_out_bl);
    chat_cornerInner[0]=resources.getDrawable(R.drawable.corner_in_tr);
    chat_cornerInner[1]=resources.getDrawable(R.drawable.corner_in_tl);
    chat_cornerInner[2]=resources.getDrawable(R.drawable.corner_in_br);
    chat_cornerInner[3]=resources.getDrawable(R.drawable.corner_in_bl);
    chat_shareDrawable=resources.getDrawable(R.drawable.share_round);
    chat_shareIconDrawable=resources.getDrawable(R.drawable.share_arrow);
    chat_replyIconDrawable=resources.getDrawable(R.drawable.fast_reply);
    chat_goIconDrawable=resources.getDrawable(R.drawable.message_arrow);
    chat_fileMiniStatesDrawable[0][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(22),R.drawable.audio_mini_arrow);
    chat_fileMiniStatesDrawable[0][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(22),R.drawable.audio_mini_arrow);
    chat_fileMiniStatesDrawable[1][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(22),R.drawable.audio_mini_cancel);
    chat_fileMiniStatesDrawable[1][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(22),R.drawable.audio_mini_cancel);
    chat_fileMiniStatesDrawable[2][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(22),R.drawable.audio_mini_arrow);
    chat_fileMiniStatesDrawable[2][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(22),R.drawable.audio_mini_arrow);
    chat_fileMiniStatesDrawable[3][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(22),R.drawable.audio_mini_cancel);
    chat_fileMiniStatesDrawable[3][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(22),R.drawable.audio_mini_cancel);
    chat_fileMiniStatesDrawable[4][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(22),R.drawable.video_mini_arrow);
    chat_fileMiniStatesDrawable[4][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(22),R.drawable.video_mini_arrow);
    chat_fileMiniStatesDrawable[5][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(22),R.drawable.video_mini_cancel);
    chat_fileMiniStatesDrawable[5][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(22),R.drawable.video_mini_cancel);
    chat_fileIcon=resources.getDrawable(R.drawable.msg_round_file_s).mutate();
    chat_flameIcon=resources.getDrawable(R.drawable.burn).mutate();
    chat_gifIcon=resources.getDrawable(R.drawable.msg_round_gif_m).mutate();
    chat_fileStatesDrawable[0][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_play_m);
    chat_fileStatesDrawable[0][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_play_m);
    chat_fileStatesDrawable[1][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_pause_m);
    chat_fileStatesDrawable[1][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_pause_m);
    chat_fileStatesDrawable[2][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_load_m);
    chat_fileStatesDrawable[2][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_load_m);
    chat_fileStatesDrawable[3][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_file_s);
    chat_fileStatesDrawable[3][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_file_s);
    chat_fileStatesDrawable[4][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_cancel_m);
    chat_fileStatesDrawable[4][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_cancel_m);
    chat_fileStatesDrawable[5][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_play_m);
    chat_fileStatesDrawable[5][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_play_m);
    chat_fileStatesDrawable[6][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_pause_m);
    chat_fileStatesDrawable[6][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_pause_m);
    chat_fileStatesDrawable[7][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_load_m);
    chat_fileStatesDrawable[7][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_load_m);
    chat_fileStatesDrawable[8][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_file_s);
    chat_fileStatesDrawable[8][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_file_s);
    chat_fileStatesDrawable[9][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_cancel_m);
    chat_fileStatesDrawable[9][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_round_cancel_m);
    chat_photoStatesDrawables[0][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_load_m);
    chat_photoStatesDrawables[0][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_load_m);
    chat_photoStatesDrawables[1][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_cancel_m);
    chat_photoStatesDrawables[1][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_cancel_m);
    chat_photoStatesDrawables[2][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_gif_m);
    chat_photoStatesDrawables[2][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_gif_m);
    chat_photoStatesDrawables[3][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_play_m);
    chat_photoStatesDrawables[3][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_play_m);
    chat_photoStatesDrawables[4][0]=chat_photoStatesDrawables[4][1]=resources.getDrawable(R.drawable.burn);
    chat_photoStatesDrawables[5][0]=chat_photoStatesDrawables[5][1]=resources.getDrawable(R.drawable.circle);
    chat_photoStatesDrawables[6][0]=chat_photoStatesDrawables[6][1]=resources.getDrawable(R.drawable.photocheck);
    chat_photoStatesDrawables[7][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_load_m);
    chat_photoStatesDrawables[7][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_load_m);
    chat_photoStatesDrawables[8][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_cancel_m);
    chat_photoStatesDrawables[8][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_cancel_m);
    chat_photoStatesDrawables[9][0]=resources.getDrawable(R.drawable.doc_big).mutate();
    chat_photoStatesDrawables[9][1]=resources.getDrawable(R.drawable.doc_big).mutate();
    chat_photoStatesDrawables[10][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_load_m);
    chat_photoStatesDrawables[10][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_load_m);
    chat_photoStatesDrawables[11][0]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_cancel_m);
    chat_photoStatesDrawables[11][1]=createCircleDrawableWithIcon(AndroidUtilities.dp(48),R.drawable.msg_round_cancel_m);
    chat_photoStatesDrawables[12][0]=resources.getDrawable(R.drawable.doc_big).mutate();
    chat_photoStatesDrawables[12][1]=resources.getDrawable(R.drawable.doc_big).mutate();
    chat_contactDrawable[0]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_contact);
    chat_contactDrawable[1]=createCircleDrawableWithIcon(AndroidUtilities.dp(44),R.drawable.msg_contact);
    chat_locationDrawable[0]=createRoundRectDrawableWithIcon(AndroidUtilities.dp(2),R.drawable.msg_location);
    chat_locationDrawable[1]=createRoundRectDrawableWithIcon(AndroidUtilities.dp(2),R.drawable.msg_location);
    chat_composeShadowDrawable=context.getResources().getDrawable(R.drawable.compose_panel_shadow);
    try {
      int bitmapSize=AndroidUtilities.roundMessageSize + AndroidUtilities.dp(6);
      Bitmap bitmap=Bitmap.createBitmap(bitmapSize,bitmapSize,Bitmap.Config.ARGB_8888);
      Canvas canvas=new Canvas(bitmap);
      Paint eraserPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
      eraserPaint.setColor(0);
      eraserPaint.setStyle(Paint.Style.FILL);
      eraserPaint.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.CLEAR));
      Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG);
      paint.setShadowLayer(AndroidUtilities.dp(4),0,0,0x5f000000);
      for (int a=0; a < 2; a++) {
        canvas.drawCircle(bitmapSize / 2,bitmapSize / 2,AndroidUtilities.roundMessageSize / 2 - AndroidUtilities.dp(1),a == 0 ? paint : eraserPaint);
      }
      try {
        canvas.setBitmap(null);
      }
 catch (      Exception ignore) {
      }
      chat_roundVideoShadow=new BitmapDrawable(bitmap);
    }
 catch (    Throwable ignore) {
    }
    applyChatTheme(fontsOnly);
  }
  chat_msgTextPaintOneEmoji.setTextSize(AndroidUtilities.dp(28));
  chat_msgTextPaintTwoEmoji.setTextSize(AndroidUtilities.dp(24));
  chat_msgTextPaintThreeEmoji.setTextSize(AndroidUtilities.dp(20));
  chat_msgTextPaint.setTextSize(AndroidUtilities.dp(SharedConfig.fontSize));
  chat_msgGameTextPaint.setTextSize(AndroidUtilities.dp(14));
  chat_msgBotButtonPaint.setTextSize(AndroidUtilities.dp(15));
  if (!fontsOnly && chat_botProgressPaint != null) {
    chat_botProgressPaint.setStrokeWidth(AndroidUtilities.dp(2));
    chat_infoPaint.setTextSize(AndroidUtilities.dp(12));
    chat_docNamePaint.setTextSize(AndroidUtilities.dp(15));
    chat_locationTitlePaint.setTextSize(AndroidUtilities.dp(15));
    chat_locationAddressPaint.setTextSize(AndroidUtilities.dp(13));
    chat_audioTimePaint.setTextSize(AndroidUtilities.dp(12));
    chat_livePaint.setTextSize(AndroidUtilities.dp(12));
    chat_audioTitlePaint.setTextSize(AndroidUtilities.dp(16));
    chat_audioPerformerPaint.setTextSize(AndroidUtilities.dp(15));
    chat_botButtonPaint.setTextSize(AndroidUtilities.dp(15));
    chat_contactNamePaint.setTextSize(AndroidUtilities.dp(15));
    chat_contactPhonePaint.setTextSize(AndroidUtilities.dp(13));
    chat_durationPaint.setTextSize(AndroidUtilities.dp(12));
    chat_timePaint.setTextSize(AndroidUtilities.dp(12));
    chat_adminPaint.setTextSize(AndroidUtilities.dp(13));
    chat_namePaint.setTextSize(AndroidUtilities.dp(14));
    chat_forwardNamePaint.setTextSize(AndroidUtilities.dp(14));
    chat_replyNamePaint.setTextSize(AndroidUtilities.dp(14));
    chat_replyTextPaint.setTextSize(AndroidUtilities.dp(14));
    chat_gamePaint.setTextSize(AndroidUtilities.dp(13));
    chat_shipmentPaint.setTextSize(AndroidUtilities.dp(13));
    chat_instantViewPaint.setTextSize(AndroidUtilities.dp(13));
    chat_instantViewRectPaint.setStrokeWidth(AndroidUtilities.dp(1));
    chat_statusRecordPaint.setStrokeWidth(AndroidUtilities.dp(2));
    chat_actionTextPaint.setTextSize(AndroidUtilities.dp(Math.max(16,SharedConfig.fontSize) - 2));
    chat_contextResult_titleTextPaint.setTextSize(AndroidUtilities.dp(15));
    chat_contextResult_descriptionTextPaint.setTextSize(AndroidUtilities.dp(13));
    chat_radialProgressPaint.setStrokeWidth(AndroidUtilities.dp(3));
    chat_radialProgress2Paint.setStrokeWidth(AndroidUtilities.dp(2));
  }
}
