private void initData(){
  mModelShopCart=new ModelShopCart();
  mModelDishMenuList=new ArrayList<>();
  ArrayList<ModelDish> dishs1=new ArrayList<>();
  dishs1.add(new ModelDish("??",1.0,10));
  dishs1.add(new ModelDish("??",1.0,10));
  dishs1.add(new ModelDish("??",1.0,10));
  dishs1.add(new ModelDish("??",1.0,10));
  dishs1.add(new ModelDish("???",1.0,10));
  dishs1.add(new ModelDish("??",1.0,10));
  dishs1.add(new ModelDish("??",1.0,10));
  ModelDishMenu breakfast=new ModelDishMenu("??",dishs1);
  ArrayList<ModelDish> dishs2=new ArrayList<>();
  dishs2.add(new ModelDish("?",1.0,10));
  dishs2.add(new ModelDish("??",1.0,10));
  dishs2.add(new ModelDish("???",1.0,10));
  dishs2.add(new ModelDish("???",1.0,10));
  dishs2.add(new ModelDish("???",1.0,10));
  dishs2.add(new ModelDish("??",1.0,10));
  ModelDishMenu launch=new ModelDishMenu("??",dishs2);
  ArrayList<ModelDish> dishs3=new ArrayList<>();
  dishs3.add(new ModelDish("??",1.0,10));
  dishs3.add(new ModelDish("??",1.0,10));
  dishs3.add(new ModelDish("??",1.0,10));
  dishs3.add(new ModelDish("??",1.0,10));
  dishs3.add(new ModelDish("??",1.0,10));
  dishs3.add(new ModelDish("???",1.0,10));
  ModelDishMenu evening=new ModelDishMenu("??",dishs3);
  ArrayList<ModelDish> dishs4=new ArrayList<>();
  dishs4.add(new ModelDish("??",1.0,10));
  dishs4.add(new ModelDish("??",1.0,10));
  dishs4.add(new ModelDish("??",1.0,10));
  dishs4.add(new ModelDish("??",1.0,10));
  dishs4.add(new ModelDish("??1",1.0,10));
  dishs4.add(new ModelDish("??2",1.0,10));
  dishs4.add(new ModelDish("??3",1.0,10));
  dishs4.add(new ModelDish("??4",1.0,10));
  dishs4.add(new ModelDish("??5",1.0,10));
  dishs4.add(new ModelDish("??6",1.0,10));
  dishs4.add(new ModelDish("??7",1.0,10));
  dishs4.add(new ModelDish("??8",1.0,10));
  dishs4.add(new ModelDish("??",1.0,10));
  dishs4.add(new ModelDish("??",1.0,10));
  dishs4.add(new ModelDish("???",1.0,10));
  ModelDishMenu menu1=new ModelDishMenu("??",dishs4);
  mModelDishMenuList.add(breakfast);
  mModelDishMenuList.add(launch);
  mModelDishMenuList.add(evening);
  mModelDishMenuList.add(menu1);
}
