private void _deserialze_obj(Context context,MethodVisitor mw,Label reset_,FieldInfo fieldInfo,Class<?> fieldClass,int i){
  Label matched_=new Label();
  Label _end_if=new Label();
  mw.visitVarInsn(ALOAD,context.var("lexer"));
  mw.visitVarInsn(ALOAD,0);
  mw.visitFieldInsn(GETFIELD,context.className,fieldInfo.name + "_asm_prefix__","[C");
  mw.visitMethodInsn(INVOKEVIRTUAL,JSONLexerBase,"matchField","([C)Z");
  mw.visitJumpInsn(IFNE,matched_);
  mw.visitInsn(ACONST_NULL);
  mw.visitVarInsn(ASTORE,context.var(fieldInfo.name + "_asm"));
  mw.visitJumpInsn(GOTO,_end_if);
  mw.visitLabel(matched_);
  _setFlag(mw,context,i);
  mw.visitVarInsn(ILOAD,context.var("matchedCount"));
  mw.visitInsn(ICONST_1);
  mw.visitInsn(IADD);
  mw.visitVarInsn(ISTORE,context.var("matchedCount"));
  _deserObject(context,mw,fieldInfo,fieldClass,i);
  mw.visitVarInsn(ALOAD,1);
  mw.visitMethodInsn(INVOKEVIRTUAL,DefaultJSONParser,"getResolveStatus","()I");
  mw.visitLdcInsn(com.alibaba.fastjson.parser.DefaultJSONParser.NeedToResolve);
  mw.visitJumpInsn(IF_ICMPNE,_end_if);
  mw.visitVarInsn(ALOAD,1);
  mw.visitMethodInsn(INVOKEVIRTUAL,DefaultJSONParser,"getLastResolveTask","()" + desc(ResolveTask.class));
  mw.visitVarInsn(ASTORE,context.var("resolveTask"));
  mw.visitVarInsn(ALOAD,context.var("resolveTask"));
  mw.visitVarInsn(ALOAD,1);
  mw.visitMethodInsn(INVOKEVIRTUAL,DefaultJSONParser,"getContext","()" + desc(ParseContext.class));
  mw.visitFieldInsn(PUTFIELD,type(ResolveTask.class),"ownerContext",desc(ParseContext.class));
  mw.visitVarInsn(ALOAD,context.var("resolveTask"));
  mw.visitVarInsn(ALOAD,0);
  mw.visitLdcInsn(fieldInfo.name);
  mw.visitMethodInsn(INVOKEVIRTUAL,type(JavaBeanDeserializer.class),"getFieldDeserializer","(Ljava/lang/String;)" + desc(FieldDeserializer.class));
  mw.visitFieldInsn(PUTFIELD,type(ResolveTask.class),"fieldDeserializer",desc(FieldDeserializer.class));
  mw.visitVarInsn(ALOAD,1);
  mw.visitLdcInsn(com.alibaba.fastjson.parser.DefaultJSONParser.NONE);
  mw.visitMethodInsn(INVOKEVIRTUAL,DefaultJSONParser,"setResolveStatus","(I)V");
  mw.visitLabel(_end_if);
}
