@Override public void init(){
  h2DbHelper.update("CREATE TABLE IF NOT EXISTS TXLCN_LOG " + "(" + "ID BIGINT NOT NULL AUTO_INCREMENT, " + "UNIT_ID VARCHAR(32) NOT NULL," + "GROUP_ID VARCHAR(64) NOT NULL," + "METHOD_STR VARCHAR(512) NOT NULL ," + "BYTES BLOB NOT NULL," + "GROUP_ID_HASH BIGINT NOT NULL," + "UNIT_ID_HASH BIGINT NOT NULL," + "TIME BIGINT NOT NULL, " + "PRIMARY KEY(ID) )");
  log.info("Aspect log table finished (H2 DATABASE)");
}
