public JComponent build(){
  ComponentOrientation orientation=ComponentOrientation.getOrientation(PMS.getLocale());
  String colSpec=FormLayoutUtil.getColSpec(PANEL_COL_SPEC,orientation);
  FormLayout layout=new FormLayout(colSpec,PANEL_ROW_SPEC);
  PanelBuilder builder=new PanelBuilder(layout);
  builder.border(Borders.DLU4);
  builder.opaque(true);
  CellConstraints cc=new CellConstraints();
  initSimpleComponents(cc);
  if (!configuration.isHideAdvancedOptions()) {
    JComponent cmp=builder.addSeparator(Messages.getString("FoldTab.13"),FormLayoutUtil.flip(cc.xyw(1,1,10),colSpec,orientation));
    cmp=(JComponent)cmp.getComponent(0);
    cmp.setFont(cmp.getFont().deriveFont(Font.BOLD));
    builder.add(GuiUtil.getPreferredSizeComponent(thumbgenCheckBox),FormLayoutUtil.flip(cc.xy(1,3),colSpec,orientation));
    builder.addLabel(Messages.getString("NetworkTab.16"),FormLayoutUtil.flip(cc.xy(3,3),colSpec,orientation));
    builder.add(seekpos,FormLayoutUtil.flip(cc.xy(5,3),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(image_thumb),FormLayoutUtil.flip(cc.xy(7,3),colSpec,orientation));
    builder.addLabel(Messages.getString("FoldTab.26"),FormLayoutUtil.flip(cc.xy(1,5),colSpec,orientation));
    builder.add(audiothumbnail,FormLayoutUtil.flip(cc.xyw(3,5,3),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(mplayer_thumb),FormLayoutUtil.flip(cc.xy(7,5),colSpec,orientation));
    builder.addLabel(Messages.getString("FoldTab.27"),FormLayoutUtil.flip(cc.xy(1,7),colSpec,orientation));
    builder.add(defaultThumbFolder,FormLayoutUtil.flip(cc.xy(3,7),colSpec,orientation));
    builder.add(select,FormLayoutUtil.flip(cc.xy(5,7),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(dvdiso_thumb),FormLayoutUtil.flip(cc.xy(7,7),colSpec,orientation));
    cmp=builder.addSeparator(Messages.getString("NetworkTab.59"),FormLayoutUtil.flip(cc.xy(1,9),colSpec,orientation));
    cmp=(JComponent)cmp.getComponent(0);
    cmp.setFont(cmp.getFont().deriveFont(Font.BOLD));
    builder.addLabel(Messages.getString("FoldTab.18"),FormLayoutUtil.flip(cc.xy(1,11),colSpec,orientation));
    builder.add(sortmethod,FormLayoutUtil.flip(cc.xyw(3,11,3),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(ignorethewordthe),FormLayoutUtil.flip(cc.xy(7,11),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(prettifyfilenames),FormLayoutUtil.flip(cc.xy(1,13),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(hideextensions),FormLayoutUtil.flip(cc.xy(3,13),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(episodeTitles),FormLayoutUtil.flip(cc.xy(7,13),colSpec,orientation));
    builder.addLabel(Messages.getString("FoldTab.addSubtitlesInfo"),FormLayoutUtil.flip(cc.xy(1,15),colSpec,orientation));
    builder.add(addVideoSuffix,FormLayoutUtil.flip(cc.xyw(3,15,3),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(hideengines),FormLayoutUtil.flip(cc.xy(7,15),colSpec,orientation));
    cmp=builder.addSeparator(Messages.getString("NetworkTab.60"),FormLayoutUtil.flip(cc.xy(1,17),colSpec,orientation));
    cmp=(JComponent)cmp.getComponent(0);
    cmp.setFont(cmp.getFont().deriveFont(Font.BOLD));
    builder.add(GuiUtil.getPreferredSizeComponent(itunes),FormLayoutUtil.flip(cc.xy(1,19),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(iphoto),FormLayoutUtil.flip(cc.xy(3,19),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(aperture),FormLayoutUtil.flip(cc.xy(7,19),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(cacheenable),FormLayoutUtil.flip(cc.xy(1,21),colSpec,orientation));
    builder.add(cachereset,FormLayoutUtil.flip(cc.xyw(3,21,3),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(isShowFolderMediaLibrary),FormLayoutUtil.flip(cc.xy(7,21),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(archive),FormLayoutUtil.flip(cc.xy(1,23),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(isShowFolderServerSettings),FormLayoutUtil.flip(cc.xy(3,23),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(isShowFolderTranscode),FormLayoutUtil.flip(cc.xy(7,23),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(isShowFolderLiveSubtitles),FormLayoutUtil.flip(cc.xy(1,25),colSpec,orientation));
    builder.addLabel(Messages.getString("FoldTab.37"),FormLayoutUtil.flip(cc.xy(3,25),colSpec,orientation));
    builder.add(atzLimit,FormLayoutUtil.flip(cc.xy(5,25),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(isShowFolderNewMedia),FormLayoutUtil.flip(cc.xy(7,25),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(resume),FormLayoutUtil.flip(cc.xy(1,27),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(isShowFolderRecentlyPlayed),FormLayoutUtil.flip(cc.xy(3,27),colSpec,orientation));
    builder.add(GuiUtil.getPreferredSizeComponent(hideemptyfolders),FormLayoutUtil.flip(cc.xy(7,27),colSpec,orientation));
    builder.addLabel(Messages.getString("FoldTab.72"),FormLayoutUtil.flip(cc.xy(1,29),colSpec,orientation));
    builder.add(fullyPlayedAction,FormLayoutUtil.flip(cc.xyw(3,29,3),colSpec,orientation));
    builder.add(fullyPlayedOutputDirectory,FormLayoutUtil.flip(cc.xy(7,29),colSpec,orientation));
    builder.add(selectFullyPlayedOutputDirectory,FormLayoutUtil.flip(cc.xy(9,29),colSpec,orientation));
  }
  JPanel panel=builder.getPanel();
  panel.applyComponentOrientation(orientation);
  JScrollPane scrollPane=new JScrollPane(panel,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
  scrollPane.setBorder(BorderFactory.createEmptyBorder());
  return scrollPane;
}
