public JComponent build(){
  ComponentOrientation orientation=ComponentOrientation.getOrientation(PMS.getLocale());
  String colSpec=FormLayoutUtil.getColSpec("pref, 30dlu, fill:pref:grow, 30dlu, pref",orientation);
  FormLayout layout=new FormLayout(colSpec,"p," + "9dlu," + "fill:p:grow," + "3dlu," + "p," + "10dlu," + "[10pt,p]," + "1dlu," + "[30pt,p]," + "3dlu,");
  PanelBuilder builder=new PanelBuilder(layout);
  builder.border(Borders.DIALOG);
  builder.opaque(true);
  CellConstraints cc=new CellConstraints();
  JComponent cmp=builder.addSeparator(Messages.getString("StatusTab.9"),FormLayoutUtil.flip(cc.xyw(1,1,5),colSpec,orientation));
  cmp=(JComponent)cmp.getComponent(0);
  Font bold=cmp.getFont().deriveFont(Font.BOLD);
  Color fgColor=new Color(68,68,68);
  cmp.setFont(bold);
  renderers=new JPanel(new GuiUtil.WrapLayout(FlowLayout.CENTER,20,10));
  JScrollPane rsp=new JScrollPane(renderers,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
  rsp.setBorder(BorderFactory.createEmptyBorder());
  rsp.setPreferredSize(new Dimension(0,260));
  rsp.getHorizontalScrollBar().setLocation(0,250);
  builder.add(rsp,cc.xyw(1,3,5));
  cmp=builder.addSeparator(null,FormLayoutUtil.flip(cc.xyw(1,5,5),colSpec,orientation));
  connectedIcon.start();
  searchingIcon.start();
  disconnectedIcon.start();
  connectionStatus.setFocusable(false);
  builder.add(connectionStatus,FormLayoutUtil.flip(cc.xywh(1,7,1,3,CellConstraints.CENTER,CellConstraints.TOP),colSpec,orientation));
  setConnectionState(ConnectionState.SEARCHING);
  memBarUI=new GuiUtil.SegmentedProgressBarUI(Color.white,Color.gray);
  memBarUI.setActiveLabel("{}",Color.white,0);
  memBarUI.setActiveLabel("{}",Color.red,90);
  memBarUI.addSegment("",memColor);
  memBarUI.addSegment("",bufColor);
  memBarUI.setTickMarks(getTickMarks(),"{}");
  memoryProgressBar=new GuiUtil.CustomUIProgressBar(0,100,memBarUI);
  memoryProgressBar.setStringPainted(true);
  memoryProgressBar.setForeground(new Color(75,140,181));
  memoryProgressBar.setString(Messages.getString("StatusTab.5"));
  JLabel mem=builder.addLabel("<html><b>" + Messages.getString("StatusTab.6") + "</b> (" + Messages.getString("StatusTab.12") + ")</html>",FormLayoutUtil.flip(cc.xy(3,7),colSpec,orientation));
  mem.setForeground(fgColor);
  builder.add(memoryProgressBar,FormLayoutUtil.flip(cc.xyw(3,9,1),colSpec,orientation));
  String bitColSpec="left:pref, 3dlu, right:pref:grow";
  PanelBuilder bitrateBuilder=new PanelBuilder(new FormLayout(bitColSpec,"p, 1dlu, p, 1dlu, p"));
  bitrateLabel=new JLabel("<html><b>" + Messages.getString("StatusTab.13") + "</b> (" + Messages.getString("StatusTab.11") + ")</html>");
  bitrateLabel.setForeground(fgColor);
  bitrateBuilder.add(bitrateLabel,FormLayoutUtil.flip(cc.xy(1,1),bitColSpec,orientation));
  currentBitrateLabel=new JLabel(Messages.getString("StatusTab.14"));
  currentBitrateLabel.setForeground(fgColor);
  bitrateBuilder.add(currentBitrateLabel,FormLayoutUtil.flip(cc.xy(1,3),bitColSpec,orientation));
  currentBitrate=new JLabel("0");
  currentBitrate.setForeground(fgColor);
  bitrateBuilder.add(currentBitrate,FormLayoutUtil.flip(cc.xy(3,3),bitColSpec,orientation));
  peakBitrateLabel=new JLabel(Messages.getString("StatusTab.15"));
  peakBitrateLabel.setForeground(fgColor);
  bitrateBuilder.add(peakBitrateLabel,FormLayoutUtil.flip(cc.xy(1,5),bitColSpec,orientation));
  peakBitrate=new JLabel("0");
  peakBitrate.setForeground(fgColor);
  bitrateBuilder.add(peakBitrate,FormLayoutUtil.flip(cc.xy(3,5),bitColSpec,orientation));
  builder.add(bitrateBuilder.getPanel(),FormLayoutUtil.flip(cc.xywh(5,7,1,3,"left, top"),colSpec,orientation));
  JPanel panel=builder.getPanel();
  panel.applyComponentOrientation(orientation);
  JScrollPane scrollPane=new JScrollPane(panel,JScrollPane.VERTICAL_SCROLLBAR_NEVER,JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
  scrollPane.setBorder(BorderFactory.createEmptyBorder());
  startMemoryUpdater();
  return scrollPane;
}
