private static HystrixThreadPoolConfiguration sampleThreadPoolConfiguration(HystrixThreadPoolKey threadPoolKey,HystrixThreadPoolProperties threadPoolProperties){
  return HystrixThreadPoolConfiguration.sample(threadPoolKey,threadPoolProperties);
}
