public BitmapPrepareProducer newBitmapPrepareProducer(Producer<CloseableReference<CloseableImage>> inputProducer){
  return new BitmapPrepareProducer(inputProducer,mBitmapPrepareToDrawMinSizeBytes,mBitmapPrepareToDrawMaxSizeBytes,mBitmapPrepareToDrawForPrefetch);
}
