private void init(){
  bgPaint=new Paint(Paint.ANTI_ALIAS_FLAG);
  smallScalePaint=new Paint(Paint.ANTI_ALIAS_FLAG);
  midScalePaint=new Paint(Paint.ANTI_ALIAS_FLAG);
  lagScalePaint=new Paint(Paint.ANTI_ALIAS_FLAG);
  scaleNumPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
  resultNumPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
  unitPaint=new TextPaint(Paint.ANTI_ALIAS_FLAG);
  bgPaint.setColor(bgColor);
  smallScalePaint.setColor(smallScaleColor);
  midScalePaint.setColor(midScaleColor);
  lagScalePaint.setColor(largeScaleColor);
  scaleNumPaint.setColor(scaleNumColor);
  resultNumPaint.setColor(resultNumColor);
  unitPaint.setColor(unitColor);
  resultNumPaint.setStyle(Paint.Style.FILL);
  unitPaint.setStyle(Paint.Style.FILL);
  bgPaint.setStyle(Paint.Style.FILL);
  smallScalePaint.setStyle(Paint.Style.FILL);
  midScalePaint.setStyle(Paint.Style.FILL);
  lagScalePaint.setStyle(Paint.Style.FILL);
  lagScalePaint.setStrokeCap(Paint.Cap.ROUND);
  midScalePaint.setStrokeCap(Paint.Cap.ROUND);
  smallScalePaint.setStrokeCap(Paint.Cap.ROUND);
  smallScalePaint.setStrokeWidth(smallScaleStroke);
  midScalePaint.setStrokeWidth(midScaleStroke);
  lagScalePaint.setStrokeWidth(largeScaleStroke);
  resultNumPaint.setTextSize(resultNumTextSize);
  unitPaint.setTextSize(unitTextSize);
  scaleNumPaint.setTextSize(scaleNumTextSize);
  bgRect=new RectF();
  resultNumRect=new Rect();
  scaleNumRect=new Rect();
  kgRect=new Rect();
  resultNumPaint.getTextBounds(resultText,0,resultText.length(),resultNumRect);
  unitPaint.getTextBounds(resultText,0,1,kgRect);
  smallScaleHeight=rulerHeight / 4;
  midScaleHeight=rulerHeight / 2;
  lagScaleHeight=rulerHeight / 2 + 5;
  valueAnimator=new ValueAnimator();
}
