public static EqualToXmlPattern equalToXml(String value,boolean enablePlaceholders,String placeholderOpeningDelimiterRegex,String placeholderClosingDelimiterRegex){
  return new EqualToXmlPattern(value,enablePlaceholders,placeholderOpeningDelimiterRegex,placeholderClosingDelimiterRegex);
}
