/** 
 * Initializes Sym if first time setup.
 */
public void initSym(){
  try {
    final String tablePrefix=Latkes.getLocalProperty("jdbc.tablePrefix") + "_";
    final boolean userTableExist=JdbcRepositories.existTable(tablePrefix + User.USER);
    final boolean optionTableExist=JdbcRepositories.existTable(tablePrefix + Option.OPTION);
    if (userTableExist && optionTableExist) {
      final List<JSONObject> admins=userQueryService.getAdmins();
      if (!admins.isEmpty() && 0 < optionRepository.count()) {
        return;
      }
    }
  }
 catch (  final Exception e) {
    LOGGER.log(Level.ERROR,"Check init failed",e);
    System.exit(0);
  }
  LOGGER.info("It's your first time setup Sym, initializes Sym....");
  try {
    LOGGER.log(Level.INFO,"Database [{0}], creating all tables",Latkes.getRuntimeDatabase());
    final List<JdbcRepositories.CreateTableResult> createTableResults=JdbcRepositories.initAllTables();
    for (    final JdbcRepositories.CreateTableResult createTableResult : createTableResults) {
      LOGGER.log(Level.TRACE,"Creates table result [tableName={0}, isSuccess={1}]",createTableResult.getName(),createTableResult.isSuccess());
    }
    LOGGER.log(Level.INFO,"Created all tables, initializing database");
    final Transaction transaction=optionRepository.beginTransaction();
    JSONObject option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_STATISTIC_MEMBER_COUNT);
    option.put(Option.OPTION_VALUE,"0");
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_STATISTIC);
    optionRepository.add(option);
    option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_STATISTIC_CMT_COUNT);
    option.put(Option.OPTION_VALUE,"0");
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_STATISTIC);
    optionRepository.add(option);
    option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_STATISTIC_ARTICLE_COUNT);
    option.put(Option.OPTION_VALUE,"0");
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_STATISTIC);
    optionRepository.add(option);
    option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_STATISTIC_DOMAIN_COUNT);
    option.put(Option.OPTION_VALUE,"0");
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_STATISTIC);
    optionRepository.add(option);
    option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_STATISTIC_TAG_COUNT);
    option.put(Option.OPTION_VALUE,"0");
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_STATISTIC);
    optionRepository.add(option);
    option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_STATISTIC_LINK_COUNT);
    option.put(Option.OPTION_VALUE,"0");
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_STATISTIC);
    optionRepository.add(option);
    option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_STATISTIC_MAX_ONLINE_VISITOR_COUNT);
    option.put(Option.OPTION_VALUE,"0");
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_STATISTIC);
    optionRepository.add(option);
    option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_MISC_ALLOW_REGISTER);
    option.put(Option.OPTION_VALUE,"0");
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_MISC);
    optionRepository.add(option);
    option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_MISC_ALLOW_ANONYMOUS_VIEW);
    option.put(Option.OPTION_VALUE,"0");
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_MISC);
    optionRepository.add(option);
    option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_MISC_ALLOW_ADD_ARTICLE);
    option.put(Option.OPTION_VALUE,"0");
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_MISC);
    optionRepository.add(option);
    option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_MISC_ALLOW_ADD_COMMENT);
    option.put(Option.OPTION_VALUE,"0");
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_MISC);
    optionRepository.add(option);
    option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_MISC_LANGUAGE);
    option.put(Option.OPTION_VALUE,DEFAULT_LANG);
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_MISC);
    optionRepository.add(option);
    option=new JSONObject();
    option.put(Keys.OBJECT_ID,Option.ID_C_MISC_ARTICLE_VISIT_COUNT_MODE);
    option.put(Option.OPTION_VALUE,"0");
    option.put(Option.OPTION_CATEGORY,Option.CATEGORY_C_MISC);
    optionRepository.add(option);
    LOGGER.info("Initialized option data");
    final JSONObject permission=new JSONObject();
    permission.put(Permission.PERMISSION_CATEGORY,Permission.PERMISSION_CATEGORY_C_AD);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_AD_UPDATE_SIDE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_AD_UPDATE_BANNER);
    permissionRepository.add(permission);
    permission.put(Permission.PERMISSION_CATEGORY,Permission.PERMISSION_CATEGORY_C_ARTICLE);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_ARTICLE_ADD_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_ARTICLE_CANCEL_STICK_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_ARTICLE_REINDEX_ARTICLES_INDEX);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_ARTICLE_REINDEX_ARTICLE_INDEX);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_ARTICLE_REMOVE_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_ARTICLE_STICK_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_ARTICLE_UPDATE_ARTICLE_BASIC);
    permissionRepository.add(permission);
    permission.put(Permission.PERMISSION_CATEGORY,Permission.PERMISSION_CATEGORY_C_COMMENT);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMENT_REMOVE_COMMENT);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMENT_UPDATE_COMMENT_BASIC);
    permissionRepository.add(permission);
    permission.put(Permission.PERMISSION_CATEGORY,Permission.PERMISSION_CATEGORY_C_BREEZEMOON);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_BREEZEMOON_REMOVE_BREEZEMOON);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_BREEZEMOON_UPDATE_BREEZEMOON);
    permissionRepository.add(permission);
    permission.put(Permission.PERMISSION_CATEGORY,Permission.PERMISSION_CATEGORY_C_COMMON);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_ADD_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_ADD_ARTICLE_ANONYMOUS);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_UPDATE_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_REMOVE_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_ADD_COMMENT);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_ADD_BREEZEMOON);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_UPDATE_BREEZEMOON);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_REMOVE_BREEZEMOON);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_ADD_COMMENT_ANONYMOUS);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_UPDATE_COMMENT);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_REMOVE_COMMENT);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_VIEW_COMMENT_HISTORY);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_AT_USER);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_AT_PARTICIPANTS);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_BAD_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_BAD_COMMENT);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_EXCHANGE_INVITATION_CODE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_FOLLOW_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_WATCH_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_GOOD_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_GOOD_COMMENT);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_STICK_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_THANK_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_THANK_COMMENT);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_USE_INVITATION_LINK);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_COMMON_VIEW_ARTICLE_HISTORY);
    permissionRepository.add(permission);
    permission.put(Permission.PERMISSION_CATEGORY,Permission.PERMISSION_CATEGORY_C_DOMAIN);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_DOMAIN_ADD_DOMAIN);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_DOMAIN_ADD_DOMAIN_TAG);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_DOMAIN_REMOVE_DOMAIN);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_DOMAIN_REMOVE_DOMAIN_TAG);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_DOMAIN_UPDATE_DOMAIN_BASIC);
    permissionRepository.add(permission);
    permission.put(Permission.PERMISSION_CATEGORY,Permission.PERMISSION_CATEGORY_C_IC);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_IC_GEN_IC);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_IC_UPDATE_IC_BASIC);
    permissionRepository.add(permission);
    permission.put(Permission.PERMISSION_CATEGORY,Permission.PERMISSION_CATEGORY_C_MISC);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MISC_ALLOW_ADD_ARTICLE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MISC_ALLOW_ADD_COMMENT);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MISC_ALLOW_ANONYMOUS_VIEW);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MISC_LANGUAGE);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MISC_REGISTER_METHOD);
    permissionRepository.add(permission);
    permission.put(Permission.PERMISSION_CATEGORY,Permission.PERMISSION_CATEGORY_C_RESERVED_WORD);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_RW_ADD_RW);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_RW_REMOVE_RW);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_RW_UPDATE_RW_BASIC);
    permissionRepository.add(permission);
    permission.put(Permission.PERMISSION_CATEGORY,Permission.PERMISSION_CATEGORY_C_TAG);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_TAG_UPDATE_TAG_BASIC);
    permissionRepository.add(permission);
    permission.put(Permission.PERMISSION_CATEGORY,Permission.PERMISSION_CATEGORY_C_USER);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_USER_ADD_POINT);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_USER_ADD_USER);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_USER_DEDUCT_POINT);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_USER_EXCHANGE_POINT);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_USER_UPDATE_USER_ADVANCED);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_USER_UPDATE_USER_BASIC);
    permissionRepository.add(permission);
    permission.put(Permission.PERMISSION_CATEGORY,Permission.PERMISSION_CATEGORY_C_MENU);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN_AD);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN_ARTICLES);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN_COMMENTS);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN_DOMAINS);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN_ICS);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN_RWS);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN_TAGS);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN_USERS);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN_BREEZEMOONS);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN_MISC);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN_ROLES);
    permissionRepository.add(permission);
    permission.put(Keys.OBJECT_ID,Permission.PERMISSION_ID_C_MENU_ADMIN_REPORTS);
    permissionRepository.add(permission);
    LOGGER.info("Initialized permission data");
    final JSONObject role=new JSONObject();
    role.put(Keys.OBJECT_ID,Role.ROLE_ID_C_ADMIN);
    role.put(Role.ROLE_NAME,"Admin");
    role.put(Role.ROLE_DESCRIPTION,"");
    roleRepository.add(role);
    role.put(Keys.OBJECT_ID,Role.ROLE_ID_C_DEFAULT);
    role.put(Role.ROLE_NAME,"Default");
    role.put(Role.ROLE_DESCRIPTION,"");
    roleRepository.add(role);
    role.put(Keys.OBJECT_ID,Role.ROLE_ID_C_LEADER);
    role.put(Role.ROLE_NAME,"Leader");
    role.put(Role.ROLE_DESCRIPTION,"");
    roleRepository.add(role);
    role.put(Keys.OBJECT_ID,Role.ROLE_ID_C_MEMBER);
    role.put(Role.ROLE_NAME,"Member");
    role.put(Role.ROLE_DESCRIPTION,"");
    roleRepository.add(role);
    role.put(Keys.OBJECT_ID,Role.ROLE_ID_C_REGULAR);
    role.put(Role.ROLE_NAME,"Regular");
    role.put(Role.ROLE_DESCRIPTION,"");
    roleRepository.add(role);
    role.put(Keys.OBJECT_ID,Role.ROLE_ID_C_VISITOR);
    role.put(Role.ROLE_NAME,"Visitor");
    role.put(Role.ROLE_DESCRIPTION,"");
    roleRepository.add(role);
    LOGGER.info("Initialized role data");
    final JSONObject rolePermission=new JSONObject();
    rolePermission.put(Role.ROLE_ID,Role.ROLE_ID_C_DEFAULT);
    for (    final String permissionId : DEFAULT_PERMISSIONS) {
      rolePermission.put(Keys.OBJECT_ID,Ids.genTimeMillisId());
      rolePermission.put(Permission.PERMISSION_ID,permissionId);
      rolePermissionRepository.add(rolePermission);
    }
    rolePermission.put(Role.ROLE_ID,Role.ROLE_ID_C_MEMBER);
    for (    final String permissionId : MEMBER_PERMISSIONS) {
      rolePermission.put(Keys.OBJECT_ID,Ids.genTimeMillisId());
      rolePermission.put(Permission.PERMISSION_ID,permissionId);
      rolePermissionRepository.add(rolePermission);
    }
    rolePermission.put(Role.ROLE_ID,Role.ROLE_ID_C_REGULAR);
    for (    final String permissionId : REGULAR_PERMISSIONS) {
      rolePermission.put(Keys.OBJECT_ID,Ids.genTimeMillisId());
      rolePermission.put(Permission.PERMISSION_ID,permissionId);
      rolePermissionRepository.add(rolePermission);
    }
    rolePermission.put(Role.ROLE_ID,Role.ROLE_ID_C_LEADER);
    for (    final String permissionId : LEADER_PERMISSIONS) {
      rolePermission.put(Keys.OBJECT_ID,Ids.genTimeMillisId());
      rolePermission.put(Permission.PERMISSION_ID,permissionId);
      rolePermissionRepository.add(rolePermission);
    }
    rolePermission.put(Role.ROLE_ID,Role.ROLE_ID_C_ADMIN);
    for (    final String permissionId : ADMIN_PERMISSIONS) {
      rolePermission.put(Keys.OBJECT_ID,Ids.genTimeMillisId());
      rolePermission.put(Permission.PERMISSION_ID,permissionId);
      rolePermissionRepository.add(rolePermission);
    }
    LOGGER.info("Initialized role-permission data");
    transaction.commit();
    final JSONObject admin=new JSONObject();
    admin.put(User.USER_EMAIL,"admin" + UserExt.USER_BUILTIN_EMAIL_SUFFIX);
    admin.put(User.USER_NAME,"admin");
    admin.put(User.USER_PASSWORD,DigestUtils.md5Hex("admin"));
    admin.put(UserExt.USER_LANGUAGE,DEFAULT_LANG);
    admin.put(User.USER_ROLE,Role.ROLE_ID_C_ADMIN);
    admin.put(UserExt.USER_STATUS,UserExt.USER_STATUS_C_VALID);
    admin.put(UserExt.USER_GUIDE_STEP,UserExt.USER_GUIDE_STEP_FIN);
    admin.put(UserExt.USER_AVATAR_URL,AvatarQueryService.DEFAULT_AVATAR_URL);
    final String adminId=userMgmtService.addUser(admin);
    admin.put(Keys.OBJECT_ID,adminId);
    final JSONObject comBot=new JSONObject();
    comBot.put(User.USER_EMAIL,UserExt.COM_BOT_EMAIL);
    comBot.put(User.USER_NAME,UserExt.COM_BOT_NAME);
    comBot.put(User.USER_PASSWORD,DigestUtils.md5Hex(String.valueOf(new Random().nextInt())));
    comBot.put(UserExt.USER_LANGUAGE,"en_US");
    comBot.put(UserExt.USER_GUIDE_STEP,UserExt.USER_GUIDE_STEP_FIN);
    comBot.put(User.USER_ROLE,Role.ROLE_ID_C_DEFAULT);
    comBot.put(UserExt.USER_STATUS,UserExt.USER_STATUS_C_VALID);
    userMgmtService.addUser(comBot);
    LOGGER.info("Initialized admin user");
    String tagTitle=Symphonys.SYS_ANNOUNCE_TAG;
    String tagId=tagMgmtService.addTag(adminId,tagTitle);
    JSONObject tag=tagRepository.get(tagId);
    tag.put(Tag.TAG_URI,"announcement");
    tagMgmtService.updateTag(tagId,tag);
    tagTitle="Sym";
    tagId=tagMgmtService.addTag(adminId,tagTitle);
    tag=tagRepository.get(tagId);
    tag.put(Tag.TAG_URI,"sym");
    tag.put(Tag.TAG_ICON_PATH,"sym.png");
    tag.put(Tag.TAG_DESCRIPTION,"[Sym](https://github.com/b3log/symphony) ???? Java ???????????/BBS/????/??????“???????????????”?");
    tagMgmtService.updateTag(tagId,tag);
    LOGGER.log(Level.INFO,"Initialized tag data");
    final JSONObject article=new JSONObject();
    article.put(Article.ARTICLE_TITLE,"???? Sym ?? :gift_heart:");
    article.put(Article.ARTICLE_TAGS,"????,Sym");
    article.put(Article.ARTICLE_CONTENT,"???????????????????????");
    article.put(Article.ARTICLE_EDITOR_TYPE,0);
    article.put(Article.ARTICLE_AUTHOR_ID,admin.optString(Keys.OBJECT_ID));
    articleMgmtService.addArticle(article);
    LOGGER.info("Initialized Sym, have fun!");
  }
 catch (  final Exception e) {
    LOGGER.log(Level.ERROR,"Initializes Sym failed",e);
    System.exit(0);
  }
}
