public static void setSkipJvmReferenceHealthCheck(ClassLoader classLoader,boolean skipJvmReferenceHealthCheck){
  skipJvmReferenceHealthCheckMap.putIfAbsent(classLoader,skipJvmReferenceHealthCheck);
}
