@Bean public SwitcherMethodMatcherPointcutAdvisor switcherMethodMatcherPointcutAdvisor(List<DataSourceSwitchStrategyMatcher> matchers,List<TableSwitchStrategyMatcher> tableSwitcher){
  return new SwitcherMethodMatcherPointcutAdvisor(matchers,tableSwitcher);
}
