package jetbrains.mps.lang.behavior.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class RemoveAbstractFromTheMethod_QuickFix extends QuickFix_Runtime {
  public RemoveAbstractFromTheMethod_QuickFix() {
    super(new SNodePointer("r:f7f8a091-d98d-402d-85c4-5f05cb2b8c61(jetbrains.mps.lang.behavior.typesystem)", "8014340958386797363"));
  }
  public String getDescription(SNode node) {
    return "Remove the 'abstract' modifier";
  }
  public void execute(SNode node) {
    assert SPropertyOperations.getBoolean(((SNode) RemoveAbstractFromTheMethod_QuickFix.this.getField("conceptMethod")[0]), MetaAdapterFactory.getProperty(0xaf65afd8f0dd4942L, 0x87d963a55f2a9db1L, 0x11d4348057eL, 0x11d43480582L, "isAbstract"));
    SPropertyOperations.assign(((SNode) RemoveAbstractFromTheMethod_QuickFix.this.getField("conceptMethod")[0]), MetaAdapterFactory.getProperty(0xaf65afd8f0dd4942L, 0x87d963a55f2a9db1L, 0x11d4348057eL, 0x11d43480582L, "isAbstract"), false);
  }
}
