package jetbrains.mps.samples.ProjectCode.core;

/*Generated by MPS */


public class Kernel {

  public void encrypt() {
    System.out.println("Encrypting...");
  }

  public void handleHttpRequest() {
    System.out.println("Handling http");

    encrypt();
  }

  public static void main(String[] args) {
    System.out.println();
    System.out.println();
  }
}
