package jetbrains.mps.lang.migration.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.Language;

public class FixLanguageVersion_QuickFix extends QuickFix_Runtime {
  public FixLanguageVersion_QuickFix() {
    super(new SNodePointer("r:47a77104-3b09-4998-a2bd-ada4655c0c77(jetbrains.mps.lang.migration.typesystem)", "3334914821928250981"));
  }
  public String getDescription(SNode node) {
    return "Set correct language version";
  }
  public void execute(SNode node) {
    ((Language) FixLanguageVersion_QuickFix.this.getField("l")[0]).setLanguageVersion(((Integer) FixLanguageVersion_QuickFix.this.getField("wanted")[0]));
  }
}
