package jetbrains.mps.baseLanguage.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class replaceNode_QuickFix extends QuickFix_Runtime {
  public replaceNode_QuickFix() {
    super(new SNodePointer("r:00000000-0000-4000-0000-011c895902c5(jetbrains.mps.baseLanguage.typesystem)", "2364881513287750938"));
  }
  public void execute(SNode node) {
    // FIXME split into specific quick fixes 
    SNodeOperations.replaceWithAnother(node, ((SNode) replaceNode_QuickFix.this.getField("newNode")[0]));
  }
}
