package jetbrains.mps.lang.editor.enumMigration;

/*Generated by MPS */

import org.jetbrains.mps.openapi.language.SEnumerationLiteral;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;

public class _Colors_Enum_MigrationUtils {
  public static String value(SEnumerationLiteral enummember) {
    switch (enumSwitchIndex_fc3uyg_a0a0a.indexNullable(enummember)) {
      case 0:
        return null;
      case 1:
        return "red";
      case 2:
        return "pink";
      case 3:
        return "orange";
      case 4:
        return "yellow";
      case 5:
        return "green";
      case 6:
        return "DARK_GREEN";
      case 7:
        return "magenta";
      case 8:
        return "DARK_MAGENTA";
      case 9:
        return "cyan";
      case 10:
        return "blue";
      case 11:
        return "LIGHT_BLUE";
      case 12:
        return "DARK_BLUE";
      case 13:
        return "gray";
      case 14:
        return "lightGray";
      case 15:
        return "darkGray";
      case 16:
        return "WHITE";
      case 17:
        return "black";
      default:
        return null;
    }
  }
  public static SEnumerationLiteral fromValue(String value) {
    if (value == null) {
      return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0xfc609b3d56L, "none");
    }
    switch (value) {
      case "red":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0xfc609b3d57L, "red");
      case "pink":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0xfc609b3d58L, "pink");
      case "orange":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0xfc609b3d59L, "orange");
      case "yellow":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0xfc609b3d5aL, "yellow");
      case "green":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0xfc609b3d5bL, "green");
      case "DARK_GREEN":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0x100656b782aL, "darkGreen");
      case "magenta":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0xfc609b3d5cL, "magenta");
      case "DARK_MAGENTA":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0x100656bb6ddL, "darkMagenta");
      case "cyan":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0xfc609b3d5dL, "cyan");
      case "blue":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0xfc609b3d5eL, "blue");
      case "LIGHT_BLUE":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0x11b375eefccL, "lightBlue");
      case "DARK_BLUE":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0x100653ae118L, "darkBlue");
      case "gray":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0xfc6fdd4165L, "gray");
      case "lightGray":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0xfc6fdd4166L, "lightGray");
      case "darkGray":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0xfc6fdd4167L, "darkGray");
      case "WHITE":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0x11abf9b4043L, "white");
      case "black":
        return SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, "jetbrains.mps.lang.editor.structure._Colors_Enum"), 0x633fb1d6ccc28638L, "black");
      default:
        return null;
    }
  }
  private static EnumerationLiteralsIndex enumSwitchIndex_fc3uyg_a0a0a = EnumerationLiteralsIndex.build(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xfc609b3d55L, 0xfc609b3d56L, 0xfc609b3d57L, 0xfc609b3d58L, 0xfc609b3d59L, 0xfc609b3d5aL, 0xfc609b3d5bL, 0x100656b782aL, 0xfc609b3d5cL, 0x100656bb6ddL, 0xfc609b3d5dL, 0xfc609b3d5eL, 0x11b375eefccL, 0x100653ae118L, 0xfc6fdd4165L, 0xfc6fdd4166L, 0xfc6fdd4167L, 0x11abf9b4043L, 0x633fb1d6ccc28638L);
}
